/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author 8_user
 */
public class Armar extends javax.swing.JFrame {

    /**
     * Creates new form Armar
     */
    public Armar() {
        initComponents();
        this.setLocationRelativeTo(null);
        bGroupLocacion.add(bosque);
        bGroupLocacion.add(casa);
        bGroupLocacion.add(castillo);
        bGroupLocacion.add(ciudad);
    }
    
    public String personaje1="",personaje2="",personaje3="",lugar="",des="";
    public int personajes=0;
    
    public Image getIconImage(){
     Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retvalue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupLocacion = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        Comenzar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        niño = new javax.swing.JCheckBox();
        niña = new javax.swing.JCheckBox();
        hombre = new javax.swing.JCheckBox();
        mujer = new javax.swing.JCheckBox();
        Finales = new javax.swing.JComboBox<>();
        bosque = new javax.swing.JRadioButton();
        casa = new javax.swing.JRadioButton();
        ciudad = new javax.swing.JRadioButton();
        castillo = new javax.swing.JRadioButton();
        jLabelFondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        Atras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 110, 30));

        Comenzar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Comenzar.setText("Comenzar");
        Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(Comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccionar personajes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Locación");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        niño.setBackground(new java.awt.Color(204, 204, 204));
        niño.setForeground(new java.awt.Color(255, 255, 255));
        niño.setText("Niño");
        niño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niñoActionPerformed(evt);
            }
        });
        niño.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                niñoPropertyChange(evt);
            }
        });
        getContentPane().add(niño, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, 40));

        niña.setBackground(new java.awt.Color(204, 204, 204));
        niña.setForeground(new java.awt.Color(255, 255, 255));
        niña.setText("Niña");
        niña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niñaActionPerformed(evt);
            }
        });
        getContentPane().add(niña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, 40));

        hombre.setBackground(new java.awt.Color(204, 204, 204));
        hombre.setForeground(new java.awt.Color(255, 255, 255));
        hombre.setText("Hombre");
        getContentPane().add(hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, 40));

        mujer.setBackground(new java.awt.Color(204, 204, 204));
        mujer.setForeground(new java.awt.Color(255, 255, 255));
        mujer.setText("Mujer");
        getContentPane().add(mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 110, 40));

        Finales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Finales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dramatico", "triste", "feliz", "chistoso" }));
        getContentPane().add(Finales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 200, -1));

        bosque.setBackground(new java.awt.Color(204, 204, 204));
        bGroupLocacion.add(bosque);
        bosque.setForeground(new java.awt.Color(255, 255, 255));
        bosque.setText("Bosque");
        bosque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosqueActionPerformed(evt);
            }
        });
        getContentPane().add(bosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 70, -1));

        casa.setBackground(new java.awt.Color(204, 204, 204));
        bGroupLocacion.add(casa);
        casa.setForeground(new java.awt.Color(255, 255, 255));
        casa.setText("Casa");
        casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casaActionPerformed(evt);
            }
        });
        getContentPane().add(casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 70, -1));

        ciudad.setBackground(new java.awt.Color(204, 204, 204));
        bGroupLocacion.add(ciudad);
        ciudad.setForeground(new java.awt.Color(255, 255, 255));
        ciudad.setText("Ciudad");
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });
        getContentPane().add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 80, -1));

        castillo.setBackground(new java.awt.Color(204, 204, 204));
        bGroupLocacion.add(castillo);
        castillo.setForeground(new java.awt.Color(255, 255, 255));
        castillo.setText("Castillo");
        castillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castilloActionPerformed(evt);
            }
        });
        getContentPane().add(castillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 80, -1));

        jLabelFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventana2.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
       // TODO add your handling code here:
        Index index = new Index();
        index.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void bosqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosqueActionPerformed
        // TODO add your handling code here:
        lugar="bosque";
    }//GEN-LAST:event_bosqueActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
        lugar="ciudad";
    }//GEN-LAST:event_ciudadActionPerformed

    private void niñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niñoActionPerformed

    private void niñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niñaActionPerformed

    private void niñoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_niñoPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_niñoPropertyChange

    private void ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarActionPerformed
        // TODO add your handling code here:
        if(niño.isSelected()&niña.isSelected()&hombre.isSelected()&mujer.isSelected()){
        JOptionPane.showMessageDialog(null,"Por favor, selecciona de 0 a 3 personajes.");
         }
      else{
          if(niño.isSelected()){
              if(!personaje1.equals("")){
                  if(!personaje2.equals("")){
                      if(personaje3.equals("")){
                          personaje3="nino";
                      }
                  }
                  else{
                          personaje2="nino";
                      }
              }
              else{
                  personaje1="nino";
              }
          }
          if(niña.isSelected()){
              if(!personaje1.equals("")){
                  if(!personaje2.equals("")){
                      if(personaje3.equals("")){
                          personaje3="nina";
                      }
                  }
                      else{
                          personaje2="nina";
                      }
              }
              else{
                  personaje1="nina";
              }
          }
          if(hombre.isSelected()){
              if(!personaje1.equals("")){
                  if(!personaje2.equals("")){
                      if(personaje3.equals("")){
                          personaje3="hombre";
                      }
                  }
                      else{
                          personaje2="hombre";
                      }
              }
              else{
                  personaje1="hombre";
              }
          }
          if(mujer.isSelected()){
              if(!personaje1.equals("")){
                  if(!personaje2.equals("")){
                      if(personaje3.equals("")){
                          personaje3="mujer";
                      }
                  }
                      else{
                          personaje2="mujer";
                      }
              }
              else{
                  personaje1="mujer";
              }
          }
          if(!personaje1.equals("")&personaje2.equals("")&personaje3.equals("")){
              personajes=1;
          }
          if(!personaje1.equals("")&!personaje2.equals("")&personaje3.equals("")){
              personajes=2;
          }
          if(!personaje1.equals("")&!personaje2.equals("")&!personaje3.equals("")){
              personajes=3;
          }
          des=Finales.getSelectedItem().toString();
          Cuento cuento = new Cuento(personaje1,personaje2,personaje3,lugar,des,personajes);
          cuento.setVisible(true);
          this.dispose();
      }
    }//GEN-LAST:event_ComenzarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,lugar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void castilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castilloActionPerformed
        // TODO add your handling code here:
        lugar="castillo";
    }//GEN-LAST:event_castilloActionPerformed

    private void casaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casaActionPerformed
        // TODO add your handling code here:
        lugar="casa";
    }//GEN-LAST:event_casaActionPerformed

    public String ConseguirLugar (){
        String lugar="";
        if(bosque.isSelected()){
            lugar="bosque";
        }
        if(casa.isSelected()){
            lugar="casa";
        }
        if(castillo.isSelected()){
            lugar="castillo";
        }
        if(ciudad.isSelected()){
            lugar="ciudad";
        }
        return lugar;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Armar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Armar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Armar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Armar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Armar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Comenzar;
    private javax.swing.JComboBox<String> Finales;
    private javax.swing.ButtonGroup bGroupLocacion;
    private javax.swing.JRadioButton bosque;
    private javax.swing.JRadioButton casa;
    private javax.swing.JRadioButton castillo;
    private javax.swing.JRadioButton ciudad;
    private javax.swing.JCheckBox hombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondo2;
    private javax.swing.JCheckBox mujer;
    private javax.swing.JCheckBox niña;
    private javax.swing.JCheckBox niño;
    // End of variables declaration//GEN-END:variables
}
